
'''
Add a dict, then save it as a .json file. To read it, just use json.load().
'''

import json

name_mappings = {
    'ATL': 'Falcons',
    'BUF': 'Bills',
    'JAX': 'Jaguars',
    'DAL': 'Cowboys',
    'GB': 'Packers',
    'IND': 'Colts',
    'MIA': 'Dolphins',
    'MIN': 'Vikings',
    'TB': 'Buccaneers',
    'NYG': 'Giants',
    'OAK': 'Raiders',
    'BAL': 'Ravens',
    'WAS': 'Redskins',
    'LAR': 'Rams',
    'ARI': 'Cardinals',
    'CIN': 'Bengals',
    'DEN': 'Broncos',
    'PHI': 'Eagles',
    'LAC': 'Chargers',
    'CAR': 'Panthers',
    'TEN': 'Titans',
    'NYJ': 'Jets',
    'CHI': 'Bears',
    'PIT': 'Steelers',
    'KC': 'Chiefs',
    'NE': 'Patriots',
    'SEA': 'Seahawks',
    'NO': 'Saints',
    'DET': 'Lions',
    'SF': '49ers',
    'CLE': 'Browns',
    'HOU': 'Texans',
}

team_abbr = {
    'Tampa Bay Buccaneers': 'TB', 
    'Buffalo Bills': 'BUF', 
    'Chicago Bears': 'CHI',
    'Denver Broncos': 'DEN',
    'Kansas City Chiefs': 'KC',
    'Los Angeles Rams': 'LAR',
    'Minnesota Vikings': 'MIN',
    'New Orleans Saints': 'NO',
    'New York Jets': 'NYJ',
    'Chicago Bears': 'CHI',
    'Denver Broncos': 'DEN',
    'Philadelphia Eagles': 'PHI', 
    'Seattle Seahawks': 'SEA', 
    'St. Louis Cardinals': 'ARI',
    'Washington Redskins': 'WAS',
    'New England Patriots': 'NE', 
    'Baltimore Colts': 'IND',
    'Detroit Lions': 'DET', 
    'Green Bay Packers': 'GB', 
    'Miami Dolphins': 'MIA',
    'New York Giants': 'NYG', 
    'Pittsburgh Steelers': 'PIT', 
    'San Diego Chargers': 'LAC',
    'San Francisco 49ers': 'SF', 
    'Atlanta Falcons': 'ATL', 
    'Cincinnati Bengals': 'CIN',
    'Cleveland Browns': 'CLE', 
    'Dallas Cowboys': 'DAL', 
    'Houston Oilers': 'HOU',
    'Oakland Raiders': 'LV', 
    'Los Angeles Raiders': 'LV', 
    'Indianapolis Colts': 'IND',
    'Phoenix Cardinals': 'ARI', 
    'Arizona Cardinals': 'ARI', 
    'Jacksonville Jaguars': 'JAX',
    'St. Louis Rams': 'LAR', 
    'Carolina Panthers': 'CAR', 
    'Baltimore Ravens': 'BAL',
    'Tennessee Oilers': 'TEN', 
    'Tennessee Titans': 'TEN', 
    'Houston Texans': 'HOU',
    'Los Angeles Chargers': 'LAC', 
    'Washington Football Team': 'WAS',
    'Las Vegas Raiders': 'LV'}

sched_dict1 = {
    'WildCard': 18,
    'Wildcard': 18,
    'Division': 19,
    'Conference': 20,
    'SuperBowl': 21,
    'Superbowl': 21
}

sched_dict2 = {
    'WildCard': 19,
    'Wildcard': 19,
    'Division': 20,
    'Conference': 21,
    'SuperBowl': 22,
    'Superbowl': 22
}


# Serialize data into file:
json.dump(name_mappings, open( "data/name_mappings.json", 'w'))
# Read data from file:
#name_mappings_ = json.load(open("data/name_mappings.json"))

json.dump(team_abbr, open( "data/team_abbr.json", 'w'))
# Read data from file:
#team_abbr = json.load(open("data/team_abbr.json"))

json.dump(sched_dict1, open( "../data/sched_dict1.json", 'w'))
json.dump(sched_dict2, open( "../data/sched_dict2.json", 'w'))




team_abv = {
    "Cardinals": "ARI",
    "Falcons": "ATL",
    "Ravens": "BAL",
    "Bills": "BUF",
    "Panthers": "CAR",
    "Bears": "CHI",
    "Bengals": "CIN",
    "Browns": "CLE",
    "Cowboys": "DAL",
    "Broncos": "DEN",
    "Lions": "DET",
    "Packers": "GB",
    "Texans": "HOU",
    "Colts": "IND",
    "Jaguars": "JAX",
    "Chiefs": "KC",
    "Raiders": "LV",
    "Rams": "LAR",
    "Chargers": "LAC",
    "Dolphins": "MIA",
    "Vikings": "MIN",
    "Patriots": "NE",
    "Saints": "NO",
    "Giants": "NYG",
    "Jets": "NYJ",
    "Eagles": "PHI",
    "Steelers": "PIT",
    "49ers": "SF",
    "Seahawks": "SEA",
    "Buccaneers": "TB",
    "Titans": "TEN",
    "Washington": "WSH",
    "Bye": "BYE",
}

replace_dict = {
    'SD': 'LAC',
    'OAK': 'LV',
    'STL': 'LA'
}

REDUCED = {
        "Arizona": "ARI", "ARZ": "ARI",
        "Atlanta": "ATL",
        "Baltimore": "BAL",
        "Buffalo": "BUF",
        "Carolina": "CAR",
        "Chicago": "CHI",
        "Cincinnati": "CIN",
        "Cleveland": "CLE",
        "Dallas": "DAL",
        "Denver": "DEN",
        "Detroit": "DET",
        "Green Bay": "GB",
        "Houston": "HOU",
        "Indianapolis": "IND",
        "Jacksonville": "JAX",
        "Kansas City": "KC",
        "Los Angeles": "LA",
        "Miami": "MIA",
        "Minnesota": "MIN",
        "New England": "NE",
        "New Orleans": "NO",
        "NY Giants": "NYG",
        "NY Jets": "NYJ",
        "Oakland": "OAK",
        "Philadelphia": "PHI",
        "Pittsburgh": "PIT",
        "San Diego": "SD",
        "Seattle": "SEA",
        "San Francisco": "SF",
        "Tampa Bay": "TB",
        "Tennessee": "TEN",
        "Washington": "WSH"
}

ROW_NUM = {
        "ARI": 0,
        "ATL": 1,
        "BAL": 2,
        "BUF": 3,
        "CAR": 4,
        "CHI": 5,
        "CIN": 6,
        "CLE": 7,
        "DAL": 8,
        "DEN": 9,
        "DET": 10,
        "GB": 11,
        "HOU": 12,
        "IND": 13,
        "JAX": 14,
        "KC": 15,
        "LA": 16,
        "MIA": 17,
        "MIN": 18,
        "NE": 19,
        "NO": 20,
        "NYG": 21,
        "NYJ": 22,
        "OAK": 23,
        "PHI": 24,
        "PIT": 25,
        "SD": 26,
        "SEA": 27,
        "SF": 28,
        "TB": 29,
        "TEN": 30,
        "WSH": 31,
}

city_team = {
    "Vegas": "Raiders",
    "Jets": "Jets",
    "Indianapolis": "Colts",
    "Houston": "Texans",
    "Cleveland": "Browns",
    "Tennessee": "Titans",
    "Detroit": "Lions",
    "Chicago": "Bears",
    "Jacksonville": "Jaguars",
    "Orleans": "Saints",
    "Atlanta": "Falcons",
    "Angeles": "Rams",
    "Arizona": "Cardinals",
    "Giants": "Giants",
    "Seattle": "Seahawks",
    "England": "Patriots",
    "Philadelphia": "Eagles",
    "Bay": "Packers",
    "Denver": "Broncos",
    "City": "Chiefs",
    "Washington": "Washington",
    "Pittsburgh": "Steelers",
    "Buffalo": "Bills",
    "Francisco": "49ers",
    "Baltimore": "Ravens",
    "Dallas": "Cowboys",
    "Carolina": "Panthers",
    "Tampa": "Buccaneers",
    "Cincinatti": "Bengals",
    "Miami": "Dolphins",
}

divisions_dict = {
    "NFC_East": ["Eagles", "Giants", "Cowboys", "Washington"],
    "NFC North": ["Bears", "Packers", "Lions", "Vikings"],
    "NFC South": ["Buccaneers", "Saints", "Panthers", "Falcons"],
    "NFC West": ["Seahawks", "Cardinals", "Rams", "49ers"],
    "AFC East": ["Bills", "Dolphins", "Patriots", "Jets"],
    "AFC North": ["Steelers", "Ravens", "Browns", "Bengals"],
    "AFC South": ["Titans", "Colts", "Texans", "Jaguars"],
    "AFC West": ["Chiefs", "Raiders", "Broncos", "Chargers"],
}

records = {
    "Cardinals": [0, 0, 0],
    "Falcons": [0, 0, 0],
    "Ravens": [0, 0, 0],
    "Bills": [0, 0, 0],
    "Panthers": [0, 0, 0],
    "Bears": [0, 0, 0],
    "Bengals": [0, 0, 0],
    "Browns": [0, 0, 0],
    "Cowboys": [0, 0, 0],
    "Broncos": [0, 0, 0],
    "Lions": [0, 0, 0],
    "Packers": [0, 0, 0],
    "Texans": [0, 0, 0],
    "Colts": [0, 0, 0],
    "Jaguars": [0, 0, 0],
    "Chiefs": [0, 0, 0],
    "Raiders": [0, 0, 0],
    "Rams": [0, 0, 0],
    "Chargers": [0, 0, 0],
    "Dolphins": [0, 0, 0],
    "Vikings": [0, 0, 0],
    "Patriots": [0, 0, 0],
    "Saints": [0, 0, 0],
    "Giants": [0, 0, 0],
    "Jets": [0, 0, 0],
    "Eagles": [0, 0, 0],
    "Steelers": [0, 0, 0],
    "49ers": [0, 0, 0],
    "Seahawks": [0, 0, 0],
    "Buccaneers": [0, 0, 0],
    "Titans": [0, 0, 0],
    "Washington": [0, 0, 0],
}